[tool.poetry]
name = "yolov5"
version = "0.1.0"
description = ""
authors = ["Martin Højland <martin@goautonomous.io>"]

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.18.5"
opencv-python = "^4.5.5.62"
Pillow = "^9.0.0"
PyYAML = "^5.3.1"
pandas = "^1.1.4"
loguru = "^0.6.0"
filterpy = "^1.4.5"
scikit-image = "^0.19.2"
lap = "^0.4.0"
matplotlib = "^3.2.2"
requests = "^2.23.0"
scipy = "^1.4.1"
tqdm = "^4.41.0"
seaborn = "^0.11.0"
thop = "^0.0.31-2005241907"
wandb = "^0.12.15"
tensorboard = "^2.4.1"

[tool.poetry.dev-dependencies]
black = {version = "^20.8b1", allow-prereleases = true}
ipykernel = "^5.3.4"
ipywidgets = "^7.6.3"
jupyterlab = "^2.2.9"
mypy = "^0.770"
isort = "^4.3.21"
autoflake = "^1.3.1"
flake8 = "^3.7.9"
poethepoet = "^0.10.0"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--cov --cov-report=xml:cov.xml --black"
testpaths = "tests src"

[tool.coverage.paths]
source = ["src/", "*/site-packages"]

[tool.coverage.report]
show_missing = true
fail_under = 40
exclude_lines = [
  "pragma: no cover",
  "raise NotImplementedError"
]
[tool.poe.env]
DS_BUILD_CPU_ADAM = "1"

[tool.poe.tasks]
install_cuda_torch = "pip3 install torch==1.10.2+cu113 torchvision==0.11.3+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html"
install_cpu_torch = "pip3 install torch==1.10.0+cpu torchvision==0.11.1+cpu -f https://download.pytorch.org/whl/cpu/torch_stable.html"
install_cuda_libs = [
  "install_cuda_torch",
]
install_ml_cpu_libs = [ "install_cpu_torch" ]


[tool.black]
line-length = 135
target-version = ['py38']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs         # exclude a few common directories in the
  | \.git          # root of the project
  | \.mypy_cache
  | \.venv
  | \.vscode
  | _build
  | buck-out
  | build
  | dist
  | tmp
)/
'''

[tool.isort]
multi_line_output = 3
line_length = 88
include_trailing_comma = true

[build-system]
requires = ["poetry => 1.1.8"]
build-backend = "poetry.masonry.api"